name: Send Discord message on push to test2

on:
  push:
    branches:
      - test-2

jobs:
  notify-discord:
    name: Send Discord notification
    steps:
      - name: Send message to Discord
        run: |
          curl -X POST "https://discord.com/api/webhooks/1359492861376073849/UG5D1MUvgsO2cPYacgJX9md7S19nGOQ0W0cOov9IN7pcfyXW1KxJXjewK_EjWZm4FmBA" \
            -H "Content-Type: application/json" \
            -d '{
              "content": "🔔 Push detectado en `test2`. Este es un mensaje de prueba desde EAS Workflow 🎯"
            }'
