name: Create development builds
on:
  pull_request:
    branches:
      - development
       
jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development

