name: Create development builds
on:
  pull_request:
    branches:
      - development

jobs:
  build-android-apk:
    type: build
    platform: android
    project_type: expo
    params:
      profile: development 
      platform: android  
      build_artifacts:
        android:
          type: apk
      