name: Create development builds
on:
  pull_request:
    branches:
      - development

jobs:
  build-android-apk:
    type: build
    platform: android
    project_type: expo
    params:
      profile: preview
      platform: android # Se agrega la definición de la plataforma aquí
      build_artifacts:
        android:
          type: apk